### ISSUE TITLE
Towers attack entities out of range

### ISSUE THREAD

**Issue by tbvns** [WyndevCodes/Minestom-Tower-Defense#10]
If DistanceX = 2 and DistanceZ = 125, the tower would still shoot. (it's a theory)

**Comment by tbvns** [comment]
![Image](https://github.com/user-attachments/assets/8cf64c09-4cb3-4900-810b-27b4c24f07f0)

**Comment by WyndevCodes** [comment]
Regarding your above theory, I feel it is incorrect. With the current formula, a tower needs a range of just over 125 blocks (sqrt(15629)) to hit the target at where you specified.

However, I did end up fixing this, and it was just a matter of accidentally using y instead of z when calculating the distance.
